"""empty message

Revision ID: 801efec050a3
Revises: 752e10ecacc4
Create Date: 2021-11-10 17:16:00.869893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801efec050a3'
down_revision = '752e10ecacc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_name'), 'post', ['name'], unique=False)
    op.create_index(op.f('ix_post_rating'), 'post', ['rating'], unique=False)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_index('ix_tv_shows_name', table_name='tv_shows')
    op.drop_index('ix_tv_shows_timestamp', table_name='tv_shows')
    op.drop_table('tv_shows')
    op.drop_index('ix_movies_name', table_name='movies')
    op.drop_index('ix_movies_timestamp', table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movies_timestamp', 'movies', ['timestamp'], unique=False)
    op.create_index('ix_movies_name', 'movies', ['name'], unique=False)
    op.create_table('tv_shows',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tv_shows_timestamp', 'tv_shows', ['timestamp'], unique=False)
    op.create_index('ix_tv_shows_name', 'tv_shows', ['name'], unique=False)
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_rating'), table_name='post')
    op.drop_index(op.f('ix_post_name'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
